# Generated by Django 5.2.6 on 2025-09-26 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='content',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='created_at',
            new_name='stored_at',
        ),
    ]
